// 指定的当前proto语法的版本，有2和3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: protocol/protobuf/service/user.proto

// 指定生成出来的文件的package

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protocol_protobuf_service_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_service_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_service_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_protocol_protobuf_service_user_proto protoreflect.FileDescriptor

const file_protocol_protobuf_service_user_proto_rawDesc = "" +
	"\n" +
	"$protocol/protobuf/service/user.proto\x12\aservice\"4\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03ageB\fZ\n" +
	"../serviceb\x06proto3"

var (
	file_protocol_protobuf_service_user_proto_rawDescOnce sync.Once
	file_protocol_protobuf_service_user_proto_rawDescData []byte
)

func file_protocol_protobuf_service_user_proto_rawDescGZIP() []byte {
	file_protocol_protobuf_service_user_proto_rawDescOnce.Do(func() {
		file_protocol_protobuf_service_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_protobuf_service_user_proto_rawDesc), len(file_protocol_protobuf_service_user_proto_rawDesc)))
	})
	return file_protocol_protobuf_service_user_proto_rawDescData
}

var file_protocol_protobuf_service_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_protobuf_service_user_proto_goTypes = []any{
	(*User)(nil), // 0: service.User
}
var file_protocol_protobuf_service_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_protobuf_service_user_proto_init() }
func file_protocol_protobuf_service_user_proto_init() {
	if File_protocol_protobuf_service_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_protobuf_service_user_proto_rawDesc), len(file_protocol_protobuf_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_protobuf_service_user_proto_goTypes,
		DependencyIndexes: file_protocol_protobuf_service_user_proto_depIdxs,
		MessageInfos:      file_protocol_protobuf_service_user_proto_msgTypes,
	}.Build()
	File_protocol_protobuf_service_user_proto = out.File
	file_protocol_protobuf_service_user_proto_goTypes = nil
	file_protocol_protobuf_service_user_proto_depIdxs = nil
}
