---
apiVersion: v1
kind: Namespace
metadata:
  name: server-fingerprint
  labels:
    name: server-fingerprint

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-fingerprint
  namespace: server-fingerprint
  labels:
    app: server-fingerprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-fingerprint
  template:
    metadata:
      labels:
        app: server-fingerprint
    spec:
      serviceAccountName: server-fingerprint
      containers:
      - name: server-fingerprint
        image: server-fingerprint:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: GIN_MODE
          value: "release"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        # 挂载主机信息以获取更准确的硬件信息
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      # 节点选择器（可选）
      # nodeSelector:
      #   kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: server-fingerprint-service
  namespace: server-fingerprint
  labels:
    app: server-fingerprint
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: server-fingerprint

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-fingerprint
  namespace: server-fingerprint

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: server-fingerprint
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: server-fingerprint
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: server-fingerprint
subjects:
- kind: ServiceAccount
  name: server-fingerprint
  namespace: server-fingerprint

---
# 可选：Ingress 配置
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-fingerprint-ingress
  namespace: server-fingerprint
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fingerprint.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-fingerprint-service
            port:
              number: 80