# 工具配置
tools:
  servers:
    browser_search:
      api_key: "xx"
    web_crawler:
      api_key: "xx"
model:
  default_model: "deepseek-chat"
  api_key: "xx"
  base_url: "https://api.deepseek.com/"

setting:
  max_plan_iterations: 1
  max_step_num: 3